/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.wbd101.hlt010;
//Basically calling the functions in the ANDROIDHRVJNI file so it call be access the SO file for the native functions etc
public class AndroidHRVAPI {

  public static hrv_result_t HRV_Get_Analysis_Result() { //calling the function HRV_Get_Analysis_Result to get a result
    return new hrv_result_t(AndroidHRVAPIJNI.HRV_Get_Analysis_Result(), true); //calling from the SO file
  } //hrv_result_t probably holds the result
  //not sure waht the boolean true is for? validity?

  public static void init_hrv_analysis() { //initialising the hrv analysis, calling to the JNI file to access the source code
    AndroidHRVAPIJNI.init_hrv_analysis();
  }

  public static void hrv_analysis(int thistime, short hr, short rr) { //send data somewhere????? containing a time varaible, heartrate and repiratory rate
    AndroidHRVAPIJNI.hrv_analysis(thistime, hr, rr);
  }

}
