/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.wbd101.hlt010;

public class AndroidRespirationAPI {

  // Initialize respiration analsis (calls to the JNI file which inturn calls to the native methods)
  public static void init_respiration_analysis() {
    AndroidRespirationAPIJNI.init_respiration_analysis();
  }
  //Sends the parameters to the JNI file which is sent to the native methods to be calculated and returned
  public static void analyze_respiration(float this_rri) {
    AndroidRespirationAPIJNI.analyze_respiration(this_rri);
  }
  // Retrives the results from the respiration_result_t from the JNI files
  public static respiration_result_t get_respiration_result() {
    return new respiration_result_t(AndroidRespirationAPIJNI.get_respiration_result(), true);
  }

}
