/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.wbd101.hlt010;

public class AndroidRespirationAPIJNI {
  public final static native short respiration_result_t_respiratory_rate_get(long jarg1, respiration_result_t jarg1_); // Retrieves respiratory rate from the analysis result
  public final static native float respiration_result_t_respiration_current_depth_get(long jarg1, respiration_result_t jarg1_); // Retrives the current depth of repiration
  public final static native boolean respiration_result_t_is_inspirating_get(long jarg1, respiration_result_t jarg1_); // Potentially checks if the individual is in inspiration phase
  public final static native long new_respiration_result_t(); // Creates a new memory location for the respiratory results in the native code?
  public final static native void delete_respiration_result_t(long jarg1); // Deletes the repspiration result object/memory
  public final static native void init_respiration_analysis(); // Initializing respiration analysis
  public final static native void analyze_respiration(float jarg1); //Analyzers the respiration based on the provided RRI, jarg1 = RRI value
  public final static native long get_respiration_result(); // Retrieves the results from the respiration analysis

  static {
    System.loadLibrary("HRV-lib");
  }
}
